### ISSUE TITLE
CommonJS version?

### ISSUE THREAD

**Issue by oliverox** [janrg/badiDate#2]
It would be great to have a CommonJS version (or UMD version) of BadiDate. What do you think?
Ideally, I'd like to be able to just use `npm i badiDate` and use it in my code using `require`.

**Comment by janrg** [comment]
I have thought about making something like a node.js package, but I personally have no experience with it. Would you be able/willing to help with this?

**Comment by glittle** [comment]
I've got a node.js script in this project... https://github.com/glittle/badi-messenger-bot  You can take from it if it would help.

**Comment by oliverox** [comment]
Sure. I'll see what I can do.

@glittle: Cool stuff with the bot :)

**Comment by brettz9** [comment]
I'd recommend going with ES6 modules now and using something like Rollup to convert to UMD (CommonJS + AMD + global). I'd also recommend a Babel plugin to allow for using sleeker ES6 syntax now that can be converted for older browsers and using eslint (I recommend "standard") for enforcing a coding standard.

I'd also strongly suggest moving locales to own files as per best practices and specifying languages as language codes, e.g., to use with `navigator.languages`.

My hands full ATM but thought I'd make the suggestions...

Looks like a great, robust, library by the way...

**Comment by janrg** [comment]
@brettz9 I actually started doing exactly that now. I had forgotten what you had written but came to exactly that conclusion: ES6, rollup, and babel. Do you have experience with that, i.e. would you be able to answer some questions I have regarding some of the details of this process?

**Comment by brettz9** [comment]
Yes, sure! And happy Naw-Rúz!

It should actually be quite easy as you don't have any non-ES6 dependencies that need conversion (e.g., if you had CommonJS Node modules on which your library was depending--but even this isn't always too hard).

I was just doing something like this today actually. I think in your case you'd basically just want this:

A `rollup.config.js` file:

```js
import babel from 'rollup-plugin-babel';

// For minified builds, we use these two:
import uglify from 'rollup-plugin-uglify';
import {minify} from 'uglify-es';

// You can uncomment the following for converting "imports" of JSON if
//    your library ends up doing that, e.g., for internationalization
// import json from 'rollup-plugin-json';

function getRollupObject ({minifying, format = 'umd'} = {}) {
    const nonMinified = {
        // The file to convert; this should have your `export` or `export default`;
        // `export` may be better as your users might wish to only import certain methods.
        input: 'main.js',
        output: {
            format,
            file: `dist/index-${format}${minifying ? '.min' : ''}.js`,
            name: 'BadiDate' // For the name assigned as the global in the browser
        },
        plugins: [
            // json(),
            babel()
        ]
    };
    if (minifying) {
        nonMinified.plugins.push(uglify(null, minify));
    }
    return nonMinified;
};

export default [
    getRollupObject(),
    getRollupObject({minifying: true}),
    // The reason you may want the "es" format as an export format despite your code
    //   already being in ES6 modules (besides getting everything in a single file) is
    //   because the browser won't understand imports like
    //   `import XYZ from "npm-module"`, but in some new browsers (e.g., Chrome, and soon
    //    probably Firefox soon), you can already use ES6 modules in the form
    // `import XYZ from '/path/to/module';`, so a user could take advantage of modular
    //  imports with your library too since Rollup bundles the npm modules into a single
    //  bundle whose path can be targeted.
    getRollupObject({minifying: true, format: 'es'}),
    getRollupObject({minifying: false, format: 'es'})
];
```

Add the following to your `package.json` `devDependencies`:

```json
    "babel-core": "6.26.0",
    "babel-plugin-external-helpers": "^6.22.0",
    "babel-plugin-syntax-dynamic-import": "6.18.0",
    "babel-preset-env": "^1.6.1",
    "rollup": "0.57.1",
    "rollup-plugin-babel": "^3.0.3",
    "rollup-plugin-commonjs": "^9.1.0",
    "rollup-plugin-json": "^2.3.0",
    "rollup-plugin-node-builtins": "^2.1.2",
    "rollup-plugin-node-resolve": "^3.3.0",
    "rollup-plugin-re": "^1.0.6",
    "rollup-plugin-uglify": "^3.0.0",
    "uglify-es": "^3.3.9"
```

Then in the same file at a script like:

```json
"scripts": {
    "rollup": "rollup -c"
}
```

The `-c` will look for a `rollup.config.js` file as added above.

Then run `npm i` to install.

Now you can run `npm run rollup` to rollup your package. (I'd also recommend adding it to any test scripts like `"test": "npm run eslint && npm run rollup && mocha"`.)

If you try this out, I'd be happy to help, and I could also add ESLint for you if you like, to ensure your code follows, and continues to follow, best practices.

**Comment by brettz9** [comment]
Let me know if you need any help...
